# Create a data key identified in the key vault collection demo.keyvault.
from base64 import b64encode, b64decode
import os

from pymongo import MongoClient
from pymongo.encryption import ClientEncryption
from bson import binary
from bson.codec_options import CodecOptions

codec_opts = CodecOptions(uuid_representation=binary.STANDARD)

# Test key material generated by: echo $(head -c 96 /dev/urandom | base64 | tr -d '\n')
if "LOCAL_MASTERKEY_BASE64" not in os.environ:
    raise Exception("Set LOCAL_MASTERKEY_BASE64 env variable to 96 bytes of base64")

masterkey = binary.Binary(b64decode(os.environ["LOCAL_MASTERKEY_BASE64"]))

# Reset the collection.
key_vault_client = MongoClient("mongodb://localhost/")
key_vault_client.demo.keyvault.drop()